main: net.dagger.randomitemminigame.LootRushMod
name: LootRush
version: 1.2.2
description: Мини-игра в которой нужно найти случайный предмет и подставлять противников перед телепортом
authors: [nasarwo]
website:
api-version: 1.21
load: STARTUP

commands:
  lootrush:
    description: Управление мини-игрой
    usage: /lootrush <start|stop|status|role|cancel|skip|lang>
    aliases: [lr]
    permission: lootrush.admin

permissions:
  lootrush.admin:
    description: Позволяет запускать и останавливать мини-игру
    default: op
